In [1]:
# Kabir Trivedi
# 24-27-26
# Mtech Data Science
# Assignment 2

In [2]:
# Q1

# a)  Create a variable named var1 that stores an array of numbers from 0 to 30, inclusive. Print var1 and its shape.
import numpy as np
var1 = np.arange(31)
print(f'var1: {var1} \nShape: {var1.shape}')  #Printed var1 and its Shape

var1: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30] 
Shape: (31,)


In [3]:
# b) Change var2 to a validly-shaped two-dimensional matrix and store it in a new variable called var2. Print var2 and its shape.

var2 = var1[1:].reshape(5,6)   #Converting to a 2d Matrix from var1 but starting from 1 to make a validly shaped matrix
print(f'var2: {var2} \nShape: {var2.shape}')

var2: [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]] 
Shape: (5, 6)


In [4]:
# c)  Create a third variable, var3 that reshapes it into a valid three-dimensional shape. Print var3 and its shape

var3 = var1[1:].reshape(2,3,5)  #Again starting with 1 to make a valid 3 Dimensional Matrix from var1
print(f'var3: {var3} \nShape: {var3.shape}')

var3: [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]] 
Shape: (2, 3, 5)


In [5]:
# d)Use two-dimensional array indexing to set the first value in the second row of var2 to -1. Now look at var1 and var3.
#      Did they change? Explain what’s going on.  

var2[1,0] = -1
print(f'After Modifying var2 we get \nvar1: {var1} \nvar3:\n{var3}')

# Note: As we can see var1 and var3 both have the element '-1' and so it is seen that reshape() function returns a view and a copy.
#       However in come cases it might give a copy

After Modifying var2 we get 
var1: [ 0  1  2  3  4  5  6 -1  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30] 
var3:
[[[ 1  2  3  4  5]
  [ 6 -1  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]


In [6]:
# e)  Another thing that comes up a lot with array shapes is thinking about how to 
# aggregate over specific dimensions. Figure out how the NumPy sum function 
# works (and the axis argument in particular) and do the following:

# (i) Sum var3 over its second dimension and print the result.
sum_var3_over_second_dimension = np.sum(var3, axis=1)
print(f'Sum of var3 over its second dimension:\n{sum_var3_over_second_dimension}')

# (ii) Sum var3 over its third dimension and print the result.
sum_var3_over_third_dimension = np.sum(var3, axis=2)
print(f'Sum of var3 over its second dimension:\n{sum_var3_over_third_dimension}')

# (iii) Sum var3 over both its first and third dimensions and print the result.
sum_var3_over_first_and_third_dimension = np.sum(var3, axis=(0,2))
print(f'Sum of var3 over its second dimension:\n{sum_var3_over_first_and_third_dimension}')


Sum of var3 over its second dimension:
[[18 13 24 27 30]
 [63 66 69 72 75]]
Sum of var3 over its second dimension:
[[ 15  32  65]
 [ 90 115 140]]
Sum of var3 over its second dimension:
[105 147 205]


In [7]:
# f) Write code to do the following:
print(var2)
# (i) Slice out the second row of var2 and print it.
print(f'Second Row of var2: {var2[1,]}')

# (ii) Slice out the last column of var2 using the -1 notation and print it.
print(f'Last Column of var2: {var2[:,-1]}')

# (iii) Slice out the top right 2 × 2 submatrix of var2 and print it.
print(f'Top Right SubMatrix of var2:\n{var2[:2, -2:]}')

[[ 1  2  3  4  5  6]
 [-1  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
Second Row of var2: [-1  8  9 10 11 12]
Last Column of var2: [ 6 12 18 24 30]
Top Right SubMatrix of var2:
[[ 5  6]
 [11 12]]


In [8]:
# Q2

# a) The most basic kind of broadcast is with a scalar, in which you can perform a 
# binary operation (e.g., add, multiply, ...) on an array and a scalar, the effect is to 
# perform that operation with the scalar for every element of the array. To try this 
# out, create a vector 1, 2, . . . , 10 by adding 1 to the result of the arange function.

vector = np.arange(10) + 1
print(f'Vector: {vector}')

Vector: [ 1  2  3  4  5  6  7  8  9 10]


In [9]:
# b)  Now, create a 10 × 10 matrix A in which Ai j = i + j. You’ll be able to do this 
#     using the vector you just created, and adding it to a reshaped version of itself.

A = vector.reshape(10,1) + vector
print(f'10x10 Matrix with Aij = i+j using the above Vector: \n{A}')

10x10 Matrix with Aij = i+j using the above Vector: 
[[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]


In [10]:
# c) & d) A very common use of broadcasting is to standardize data, i.e., to make it have 
#    zero mean and unit variance. First, create a fake “data set” with 50 examples, 
#    each with five dimensions.

data = np.exp(np.random.randn(50, 5))
print(f'Random Data Set of Integers:\n{data}')

Random Data Set of Integers:
[[ 1.02946559  0.77684591  1.00095194  0.6355278   1.32911177]
 [ 0.21185536  0.33153988  0.81430487  0.52527702  4.48615194]
 [ 5.46054586  0.44597507  0.89148446  1.20460329  3.19372574]
 [ 1.04773276  0.21340213  0.35705604  2.20488065  0.49197177]
 [10.81529136  0.517945    1.91162135  1.60644246  1.54036398]
 [ 1.62753747  1.03178844  1.70161886  0.15586543  1.14706033]
 [ 0.70747353  0.77926212  0.19452812  0.14136259  1.8866709 ]
 [ 0.42741461  1.39197096  2.19514798  0.42238738  1.3140373 ]
 [ 0.57672187  1.18564772  3.21441879  0.5245531   1.99278971]
 [ 0.90180727  0.39525946  0.70553703  2.1377799   2.14829374]
 [ 0.29044986  0.69044798  2.62447313  1.47847042  0.82058505]
 [ 0.28437826  1.56763583  1.64952651  0.90492782 15.98483042]
 [ 0.52594027  0.73420326  1.13242341  0.69477757  0.76442682]
 [ 1.46674085  0.22906733  0.23714862  0.29228309  0.08687482]
 [ 1.08690979  0.29392741  1.8224096   1.63900378  3.56585754]
 [ 0.22964178  0.34458465 

In [11]:
# e) Now, compute the mean and standard deviation of each column.
#    This should result in two vectors of length 5. You’ll need to think a little bit about how to use 
#    the axis argument to mean and std. Store these vectors into variables and print both of them.

mean = np.mean(data, axis=0)
standard_deviation = np.std(data, axis=0)
print(f'Mean: {mean}\nStandard Deviation: {standard_deviation}')

Mean: [1.83670681 0.94900654 1.82504157 1.39416372 2.06498161]
Standard Deviation: [2.20186674 0.67955986 1.8284358  1.22971989 2.38120347]


In [12]:
# f)Now standardize the data matrix by 1) subtracting the mean off of each column, 
#   and 2) dividing each column by its standard deviation. 
#   Do this via broadcasting, and store the result in a matrix called normalized.
#   To verify that you successfully did it, compute the mean and standard deviation of
#   the columns of normalized and print them out.

normalized = (data - mean) / standard_deviation
print(f'Normalized Matrix: \n{normalized}')

normalized_mean = np.mean(normalized, axis=0)
normalized_std = np.std(normalized, axis=0)

print(f'Mean of normalized data: {normalized_mean}')
print(f'Standard deviation of normalized data: {normalized_std}')

Normalized Matrix: 
[[-3.66616751e-01 -2.53341388e-01 -4.50707449e-01 -6.16917659e-01
  -3.09032744e-01]
 [-7.37942688e-01 -9.08627339e-01 -5.52787637e-01 -7.06572862e-01
   1.01678431e+00]
 [ 1.64580308e+00 -7.40231290e-01 -5.10576919e-01 -1.54149277e-01
   4.74022545e-01]
 [-3.58320527e-01 -1.08247185e+00 -8.02864138e-01  6.59269587e-01
  -6.60594469e-01]
 [ 4.07771479e+00 -6.34324615e-01  4.73518280e-02  1.72623651e-01
  -2.20316173e-01]
 [-9.49963684e-02  1.21816924e-01 -6.75018010e-02 -1.00697590e+00
  -3.85486286e-01]
 [-5.12852691e-01 -2.49785828e-01 -8.91753190e-01 -1.01876951e+00
  -7.48826052e-02]
 [-6.40044276e-01  6.51840167e-01  2.02416957e-01 -7.90242030e-01
  -3.15363353e-01]
 [-5.72234880e-01  3.48227129e-01  7.59872029e-01 -7.07161546e-01
  -3.03174018e-02]
 [-4.24594063e-01 -8.14861374e-01 -6.12274462e-01  6.04703710e-01
   3.49874017e-02]
 [-7.02248202e-01 -3.80479461e-01  4.37221563e-01  6.85576472e-02
  -5.22591444e-01]
 [-7.05005680e-01  9.10338188e-01 -9.59919228

In [13]:
# Q3)

#  a) A Vandermonde matrix is a matrix generated from a vector in which each column 
#     of the matrix is an integer power starting from zero.

def Vandermonde(N):
    base = np.arange(N) + 1
    power = np.arange(N)
    base = base.reshape(N, 1)

    vander_matrix = base ** power
    return vander_matrix

vander = Vandermonde(12)
print(f'Vandermonde Matrix: \n{vander}')

Vandermonde Matrix: 
[[          1           1           1           1           1           1
            1           1           1           1           1           1]
 [          1           2           4           8          16          32
           64         128         256         512        1024        2048]
 [          1           3           9          27          81         243
          729        2187        6561       19683       59049      177147]
 [          1           4          16          64         256        1024
         4096       16384       65536      262144     1048576     4194304]
 [          1           5          25         125         625        3125
        15625       78125      390625     1953125     9765625    48828125]
 [          1           6          36         216        1296        7776
        46656      279936     1679616    10077696    60466176   362797056]
 [          1           7          49         343        2401       16807
       1176

In [14]:
# b)  Now, let’s make a pretend linear system problem with this matrix. Create a vector 
#     of all ones, of length 12 and call it x. Perform a matrix-vector multiplication of 
#     vander with the vector you just created and store that in a new vector and call it b. 
#     Print the vector b

x = np.ones(12)
print(f'Vector of all ones of Length 12: {x}')

b = vander @ x # or we can also use the '.dot()' function
print(f'Matrix-Vector Multiplication result: \n{b}')

Vector of all ones of Length 12: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Matrix-Vector Multiplication result: 
[1.20000000e+01 4.09500000e+03 2.65720000e+05 5.59240500e+06
 6.10351560e+07 4.35356467e+08 2.30688120e+09 1.22713351e+09
 9.43953692e+08 3.73692871e+09 3.10225064e+08 3.10073456e+09]


In [15]:
# c)  First, solve the linear system the naïve way, pretending like you don’t know x. 
#     Import numpy.linalg, invert V and multiply it by b. Print out your result. What 
#     should you get for your answer? If the answer is different than what you 
#     expected, write a sentence about that difference

import numpy.linalg as linalg

naïve_way = linalg.inv(vander) @ b
print(f'Doing it the naïve way we get: \n{naïve_way}')

# Note: The solution should be a vector of ones as x was a vector of one but as we can see some values are not exactly 1
#       because of the floating point representation.

Doing it the naïve way we get: 
[1.00000572 0.99735641 1.00311279 0.999506   1.00002861 0.99999857
 1.0000001  1.         1.         1.         1.         1.        ]


In [16]:
# d) Now, solve the same linear system using solve. Print out the result. Does it seem 
#    more or less in line with what you’d expect?

using_solve = linalg.solve(vander, b)
print(f'Using the Solve Function we get: \n{using_solve}')

# Note: The solve function provides more efficient solution than doing it the normal way as all the values are more closer to 1. 

Using the Solve Function we get: 
[1.00000067 0.99999715 1.00000411 0.99999733 1.00000089 0.99999984
 1.00000002 1.         1.         1.         1.         1.        ]


In [17]:
# https://github.com/DJKT23/Kabir_24-27-26